INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Новое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Новое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO Item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO Squery (query, person) VALUES (0, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-23, "вечер", "3 часов", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-04-28, "утро", "7 часов", "Досуг", False, True);
INSERT INTO Squery (query, person) VALUES (2, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "МФУ", 2015-04-24, "ночь", "8 часов", "Досуг", True, True);
INSERT INTO Squery (query, person) VALUES (3, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-26, "утро", "5 часов", "Досуг", True, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-05-01, "утро", "13 минут", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Коньки/ролики", 2015-04-24, "вечер", "38 минут", "Досуг", False, False);
INSERT INTO Squery (query, person) VALUES (6, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-04-26, "ночь", "6 часов", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-27, "день", "30 минут", "Досуг", False, True);
INSERT INTO Squery (query, person) VALUES (8, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-30, "утро", "22 минут", "Досуг", True, False);
INSERT INTO Squery (query, person) VALUES (9, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-04-30, "ночь", "45 минут", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-04-28, "день", "8 часов", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-05-05, "день", "6 часов", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-05-04, "вечер", "5 часов", "Досуг", False, False);
INSERT INTO Squery (query, person) VALUES (13, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-22, "ночь", "48 минут", "Досуг", True, False);
INSERT INTO Squery (query, person) VALUES (14, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-04-22, "ночь", "6 часов", "Досуг", True, False);
INSERT INTO Squery (query, person) VALUES (15, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-06, "вечер", "8 часов", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-30, "утро", "3 часов", "Досуг", False, False);
INSERT INTO Squery (query, person) VALUES (17, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-04-24, "ночь", "27 минут", "Досуг", True, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-25, "утро", "8 часов", "Досуг", False, False);
INSERT INTO Squery (query, person) VALUES (19, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-06, "вечер", "2 часов", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-04-23, "вечер", "33 минут", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-04-24, "вечер", "12 минут", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-27, "утро", "33 минут", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-27, "вечер", "5 часов", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Коньки/ролики", 2015-04-29, "день", "10 минут", "Досуг", False, False);
INSERT INTO Squery (query, person) VALUES (25, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Коньки/ролики", 2015-05-05, "вечер", "8 часов", "Досуг", True, True);
INSERT INTO Squery (query, person) VALUES (26, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-05-01, "утро", "27 минут", "Досуг", True, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-24, "ночь", "44 минут", "Досуг", False, True);
INSERT INTO Squery (query, person) VALUES (28, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-30, "утро", "4 часов", "Досуг", True, True);
INSERT INTO Squery (query, person) VALUES (29, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-29, "вечер", "1 часов", "Досуг", True, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-05-01, "утро", "3 часов", "Досуг", False, False);
INSERT INTO Squery (query, person) VALUES (31, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-28, "день", "5 часов", "Досуг", True, False);
INSERT INTO Squery (query, person) VALUES (32, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-05, "ночь", "6 часов", "Досуг", True, False);
INSERT INTO Squery (query, person) VALUES (33, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-25, "утро", "5 часов", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-26, "день", "27 минут", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-04-26, "вечер", "27 минут", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-05-01, "вечер", "8 часов", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-24, "вечер", "43 минут", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-05-01, "вечер", "2 часов", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-05-06, "утро", "39 минут", "Досуг", False, True);
INSERT INTO Squery (query, person) VALUES (40, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-05-07, "день", "46 минут", "Досуг", True, False);
INSERT INTO Squery (query, person) VALUES (41, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Настольные игры", 2015-05-05, "ночь", "1 часов", "Досуг", True, True);
INSERT INTO Squery (query, person) VALUES (42, 1);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-04-27, "утро", "14 минут", "Досуг", True, True);
INSERT INTO Squery (query, person) VALUES (43, 2);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-04-29, "вечер", "1 часов", "Досуг", True, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Коньки/ролики", 2015-04-25, "ночь", "5 часов", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-05-06, "день", "15 минут", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-04-25, "вечер", "5 часов", "Досуг", False, False);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Фото/видео техника", 2015-05-06, "день", "23 минут", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-25, "день", "28 минут", "Досуг", False, True);
INSERT INTO Query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-05-01, "вечер", "6 часов", "Досуг", False, True);
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Кино", 2015-04-24, "утро", , "Роща", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Кино", 2015-04-28, "вечер", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Поездки в магазин", 2015-04-22, "день", , "Тимирязевская", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Поездки в магазин", 2015-05-05, "ночь", , "Тимирязевская", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Поездки в магазин", 2015-04-26, "утро", , "Тимирязевская", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Вечера настольных игр", 2015-04-26, "ночь", , "Боталка", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-05-05, "утро", , "КПМ", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Поездки в магазин", 2015-04-29, "утро", , "РИО", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Выставки/семинары", 2015-04-27, "день", , "КПМ", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Выставки/семинары", 2015-04-26, "день", , "РИО", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-04-29, "утро", , "Роща", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-04-29, "день", , "РИО", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-04-26, "ночь", , "Роща", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Вечера настольных игр", 2015-04-24, "утро", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Вечера настольных игр", 2015-04-22, "вечер", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Поездки в магазин", 2015-05-05, "вечер", , "КПМ", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-05-02, "день", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-05-01, "вечер", , "Роща", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Кино", 2015-05-06, "вечер", , "КПМ", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-05-06, "вечер", , "Роща", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO Member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO Member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO Gallery (meet, uploader, link) VALUES (7, 2, "vk.com/gallery_233434424");
INSERT INTO Gallery (meet, uploader, link) VALUES (14, 1, "vk.com/gallery_233434684");
INSERT INTO Gallery (meet, uploader, link) VALUES (17, 1, "vk.com/gallery_233434411");
INSERT INTO Shop (shopName) VALUES ("Мегамагазин");
INSERT INTO Shop (shopName) VALUES ("Чудесный Московскийлавка");
INSERT INTO Shop (shopName) VALUES ("Современный Мегабар");
INSERT INTO Shop (shopName) VALUES ("Зеленый Технобар");
INSERT INTO Shop (shopName) VALUES ("Зеленый Московскиймагазин");
INSERT INTO Shop (shopName) VALUES ("Ситилавка");
INSERT INTO Shop (shopName) VALUES ("Святой Мегарынок");
INSERT INTO Shop (shopName) VALUES ("Зеленый Московскиймагазин");
INSERT INTO Shop (shopName) VALUES ("Гиперрынок");
INSERT INTO Shop (shopName) VALUES ("Совершенный Ситимаркет");
INSERT INTO ShopTag (shop, tag) VALUES (8, "Мебель");
INSERT INTO ShopTag (shop, tag) VALUES (7, "Растения");
INSERT INTO ShopTag (shop, tag) VALUES (4, "Автомобили");
INSERT INTO ShopTag (shop, tag) VALUES (9, "Техника");
INSERT INTO ShopTag (shop, tag) VALUES (7, "Еда");
INSERT INTO ShopTag (shop, tag) VALUES (6, "Еда");
INSERT INTO ShopTag (shop, tag) VALUES (7, "Мебель");
INSERT INTO ShopTag (shop, tag) VALUES (3, "Техника");
INSERT INTO ShopTag (shop, tag) VALUES (2, "Мебель");
INSERT INTO ShopTag (shop, tag) VALUES (3, "Билеты");
INSERT INTO ShopTag (shop, tag) VALUES (9, "Еда");
INSERT INTO ShopTag (shop, tag) VALUES (9, "Растения");
INSERT INTO ShopTag (shop, tag) VALUES (1, "Растения");
INSERT INTO ShopTag (shop, tag) VALUES (2, "Билеты");
INSERT INTO ShopTag (shop, tag) VALUES (2, "Растения");
INSERT INTO ShopTag (shop, tag) VALUES (3, "Растения");
INSERT INTO ShopTag (shop, tag) VALUES (9, "Билеты");
INSERT INTO ShopTag (shop, tag) VALUES (4, "Одежда");
INSERT INTO ShopTag (shop, tag) VALUES (1, "Автомобили");
INSERT INTO ShopTag (shop, tag) VALUES (2, "Растения");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 4, "Скидочная карта", 36, 2022-03-06, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 8, "Одноразовый купон", 26, 2014-06-01, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 5, "Накопительная карта", 15, 2021-10-01, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 6, "Скидочная карта", 41, 2020-12-07, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 5, "Скидочная карта", 12, 2021-03-30, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 6, "Разовая скидка", 37, 2019-04-15, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 2, "Скидочная карта", 34, 2020-09-15, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 1, "Скидочная карта", 33, 2024-01-17, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 1, "Одноразовый купон", 38, 2026-04-27, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 1, "Скидочная карта", 6, 2018-11-11, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 4, "Скидочная карта", 13, 2020-02-14, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 4, "Разовая скидка", 42, 2022-07-20, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 4, "Одноразовый купон", 22, 2015-11-21, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 8, "Накопительная карта", 33, 2021-03-16, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 5, "Разовая скидка", 5, 2022-12-19, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 1, "Одноразовый купон", 41, 2019-09-07, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 4, "Накопительная карта", 38, 2026-02-04, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 7, "Разовая скидка", 15, 2019-12-04, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 2, "Разовая скидка", 38, 2020-04-30, "скидка");
INSERT INTO Discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 6, "Накопительная карта", 37, 2022-08-08, "скидка");
