INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner_id, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-05-02, "утро", "6 часов", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (1, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-24, "утро", "4 часов", "Досуг", True, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-04-22, "вечер", "49 минут", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-30, "день", "5 часов", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-05-02, "ночь", "32 минут", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Фото/видео техника", 2015-04-25, "утро", "22 минут", "Досуг", False, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-24, "утро", "34 минут", "Досуг", False, True);
INSERT INTO app_squery (query_id, person_id) VALUES (7, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-05-07, "день", "16 минут", "Досуг", True, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Фото/видео техника", 2015-05-06, "вечер", "4 часов", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-24, "день", "7 часов", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (10, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-04-30, "ночь", "43 минут", "Досуг", True, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-27, "утро", "1 часов", "Досуг", False, True);
INSERT INTO app_squery (query_id, person_id) VALUES (12, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-04-30, "ночь", "8 часов", "Досуг", True, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-04-22, "вечер", "5 часов", "Досуг", False, True);
INSERT INTO app_squery (query_id, person_id) VALUES (14, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-04-30, "утро", "7 часов", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (15, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Cпорт инвентарь", 2015-04-25, "день", "8 часов", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (16, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-04-25, "день", "28 минут", "Досуг", True, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-05-05, "утро", "4 часов", "Досуг", False, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-27, "день", "28 минут", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Коньки/ролики", 2015-04-27, "ночь", "4 часов", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (20, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-05-04, "день", "2 часов", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (21, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-04-24, "утро", "8 часов", "Досуг", True, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "МФУ", 2015-04-23, "утро", "31 минут", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (23, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Cпорт инвентарь", 2015-04-22, "вечер", "45 минут", "Досуг", True, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-30, "ночь", "6 часов", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (25, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-05-03, "день", "20 минут", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (26, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-05-03, "ночь", "4 часов", "Досуг", True, False);
INSERT INTO app_squery (query_id, person_id) VALUES (27, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-05-02, "вечер", "5 часов", "Досуг", True, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-05-02, "вечер", "47 минут", "Досуг", False, True);
INSERT INTO app_squery (query_id, person_id) VALUES (29, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-05-06, "ночь", "3 часов", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (30, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-05-03, "утро", "11 минут", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (31, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-05-02, "вечер", "1 часов", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (32, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-27, "вечер", "28 минут", "Досуг", True, False);
INSERT INTO app_squery (query_id, person_id) VALUES (33, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Коньки/ролики", 2015-05-02, "ночь", "26 минут", "Досуг", True, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-04-30, "ночь", "2 часов", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Cпорт инвентарь", 2015-05-01, "день", "43 минут", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (36, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Cпорт инвентарь", 2015-04-27, "день", "6 часов", "Досуг", True, False);
INSERT INTO app_squery (query_id, person_id) VALUES (37, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "МФУ", 2015-05-06, "ночь", "39 минут", "Досуг", True, False);
INSERT INTO app_squery (query_id, person_id) VALUES (38, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "МФУ", 2015-04-24, "утро", "20 минут", "Досуг", True, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-28, "день", "8 часов", "Досуг", False, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-22, "ночь", "5 часов", "Досуг", False, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-04-24, "день", "46 минут", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-05-07, "день", "41 минут", "Досуг", False, True);
INSERT INTO app_squery (query_id, person_id) VALUES (43, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-05-07, "утро", "25 минут", "Досуг", True, True);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-27, "ночь", "1 часов", "Досуг", False, False);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-22, "вечер", "46 минут", "Досуг", False, False);
INSERT INTO app_squery (query_id, person_id) VALUES (46, 1);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-04, "день", "18 минут", "Досуг", True, False);
INSERT INTO app_squery (query_id, person_id) VALUES (47, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-26, "вечер", "5 часов", "Досуг", True, True);
INSERT INTO app_squery (query_id, person_id) VALUES (48, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-22, "день", "8 часов", "Досуг", True, False);
INSERT INTO app_squery (query_id, person_id) VALUES (49, 2);
INSERT INTO app_query (who_id, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Фото/видео техника", 2015-05-05, "утро", "48 минут", "Досуг", True, True);
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Остальное", 2015-04-30, "ночь", , "РИО", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Спортивные игры", 2015-04-23, "ночь", , "РИО", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-23, "утро", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-27, "день", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Поездки в магазин", 2015-04-24, "вечер", , "Боталка", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Спортивные игры", 2015-05-04, "вечер", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-29, "утро", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Кино", 2015-05-03, "день", , "Роща", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Кино", 2015-04-30, "утро", , "Тимирязевская", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Поездки в магазин", 2015-04-22, "вечер", , "КПМ", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-26, "ночь", , "Тимирязевская", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Вечера настольных игр", 2015-04-23, "утро", , "Тимирязевская", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-25, "утро", , "КПМ", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Клуб/Концерт", 2015-05-02, "утро", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-25, "утро", , "КПМ", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Остальное", 2015-04-27, "вечер", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Остальное", 2015-04-26, "ночь", , "Роща", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Кино", 2015-04-26, "утро", , "РИО", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Вечера настольных игр", 2015-05-05, "ночь", , "Конфитюр", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator_id, support, money, description, link) VALUES ("Кино", 2015-05-02, "день", , "Роща", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (17, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (17, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting_id, user_id, donate) VALUES (4, 2, 0);
INSERT INTO app_gallery (meet_id, uploader_id, link) VALUES (9, 2, "vk.com/gallery_233434659");
INSERT INTO app_gallery (meet_id, uploader_id, link) VALUES (4, 1, "vk.com/gallery_233434613");
INSERT INTO app_gallery (meet_id, uploader_id, link) VALUES (16, 1, "vk.com/gallery_233434416");
INSERT INTO app_shop (shopName) VALUES ("Зеленый  Мультирынок");
INSERT INTO app_shop (shopName) VALUES ("Зеленый Мегамаркет");
INSERT INTO app_shop (shopName) VALUES ("Святой Гипермагазин");
INSERT INTO app_shop (shopName) VALUES ("Чудесный бар");
INSERT INTO app_shop (shopName) VALUES ("Чудесный Ситимаркет");
INSERT INTO app_shop (shopName) VALUES ("Современный Ситибар");
INSERT INTO app_shop (shopName) VALUES ("Чудесный ларек");
INSERT INTO app_shop (shopName) VALUES ("Стальной Московскиймаркет");
INSERT INTO app_shop (shopName) VALUES ("Современный Мегамагазин");
INSERT INTO app_shop (shopName) VALUES ("Святой Мегарынок");
INSERT INTO app_shoptag (shop_id, tag) VALUES (2, "Автомобили");
INSERT INTO app_shoptag (shop_id, tag) VALUES (6, "Автомобили");
INSERT INTO app_shoptag (shop_id, tag) VALUES (6, "Еда");
INSERT INTO app_shoptag (shop_id, tag) VALUES (8, "Одежда");
INSERT INTO app_shoptag (shop_id, tag) VALUES (2, "Автомобили");
INSERT INTO app_shoptag (shop_id, tag) VALUES (1, "Мебель");
INSERT INTO app_shoptag (shop_id, tag) VALUES (4, "Мебель");
INSERT INTO app_shoptag (shop_id, tag) VALUES (7, "Растения");
INSERT INTO app_shoptag (shop_id, tag) VALUES (9, "Техника");
INSERT INTO app_shoptag (shop_id, tag) VALUES (8, "Растения");
INSERT INTO app_shoptag (shop_id, tag) VALUES (4, "Растения");
INSERT INTO app_shoptag (shop_id, tag) VALUES (9, "Билеты");
INSERT INTO app_shoptag (shop_id, tag) VALUES (4, "Автомобили");
INSERT INTO app_shoptag (shop_id, tag) VALUES (5, "Билеты");
INSERT INTO app_shoptag (shop_id, tag) VALUES (6, "Автомобили");
INSERT INTO app_shoptag (shop_id, tag) VALUES (3, "Билеты");
INSERT INTO app_shoptag (shop_id, tag) VALUES (8, "Одежда");
INSERT INTO app_shoptag (shop_id, tag) VALUES (3, "Автомобили");
INSERT INTO app_shoptag (shop_id, tag) VALUES (2, "Техника");
INSERT INTO app_shoptag (shop_id, tag) VALUES (2, "Билеты");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 7, "Одноразовый купон", 34, 2018-06-21, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 7, "Разовая скидка", 10, 2022-03-28, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 5, "Разовая скидка", 27, 2016-10-04, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 4, "Одноразовый купон", 25, 2019-08-28, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 1, "Одноразовый купон", 22, 2014-03-12, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 4, "Разовая скидка", 43, 2013-05-28, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 6, "Разовая скидка", 14, 2023-03-27, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 7, "Одноразовый купон", 41, 2023-04-03, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 9, "Одноразовый купон", 39, 2024-03-13, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 6, "Разовая скидка", 22, 2020-05-09, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 9, "Разовая скидка", 32, 2020-01-10, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 5, "Накопительная карта", 6, 2020-07-24, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 4, "Скидочная карта", 8, 2023-12-20, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 3, "Скидочная карта", 10, 2018-08-22, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 7, "Скидочная карта", 27, 2014-02-04, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 5, "Одноразовый купон", 41, 2016-11-28, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 5, "Скидочная карта", 41, 2014-03-13, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 4, "Разовая скидка", 10, 2015-03-20, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (1, 5, "Скидочная карта", 20, 2018-05-29, "скидка");
INSERT INTO app_discount (owner_id, shop_id, discountType, discount, expTime, description) VALUES (2, 4, "Скидочная карта", 30, 2024-09-17, "скидка");
