INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 2, "Плохое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Хорошее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 1, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Новое", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Среднее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 2, "Хорошее", "my room", True, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 2, "Новое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "МФУ", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Новое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Игровые приставки", 2, "Плохое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Новое", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Cпорт инвентарь", 1, "Хорошее", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Велики", 2, "Среднее", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Конспекты/задания", 1, "Плохое", "my room", False, False, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Хоз. предметы", 2, "Плохое", "my room", False, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Коньки/ролики", 1, "Среднее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Настольные игры", 2, "Хорошее", "my room", True, True, "need money, use it");
INSERT INTO app_item (name, itemType, owner, quality, location, status, isCommon, description) VALUES ("Моя вещь", "Фото/видео техника", 1, "Среднее", "my room", False, False, "need money, use it");
INSERT INTO app_squery (query, person) VALUES (0, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-03, "вечер", "18 минут", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-22, "утро", "44 минут", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-05-01, "ночь", "4 часов", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-04-25, "день", "8 часов", "Досуг", False, False);
INSERT INTO app_squery (query, person) VALUES (4, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-24, "вечер", "15 минут", "Досуг", True, True);
INSERT INTO app_squery (query, person) VALUES (5, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-05-01, "день", "22 минут", "Досуг", True, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Cпорт инвентарь", 2015-04-30, "ночь", "33 минут", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (7, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-24, "день", "31 минут", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Фото/видео техника", 2015-04-28, "вечер", "20 минут", "Досуг", False, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "МФУ", 2015-05-04, "вечер", "36 минут", "Досуг", False, False);
INSERT INTO app_squery (query, person) VALUES (10, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-01, "вечер", "34 минут", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-04-22, "утро", "13 минут", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (12, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Коньки/ролики", 2015-04-27, "утро", "6 часов", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (13, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Коньки/ролики", 2015-04-30, "ночь", "1 часов", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-04-30, "утро", "8 часов", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (15, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-04-26, "день", "43 минут", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-05-03, "ночь", "44 минут", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-04-22, "вечер", "1 часов", "Досуг", False, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-06, "утро", "3 часов", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (19, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Cпорт инвентарь", 2015-05-01, "вечер", "6 часов", "Досуг", True, True);
INSERT INTO app_squery (query, person) VALUES (20, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "МФУ", 2015-05-01, "день", "48 минут", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-05-04, "вечер", "1 часов", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-05-07, "вечер", "39 минут", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-22, "утро", "43 минут", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (24, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-05-07, "день", "28 минут", "Досуг", True, True);
INSERT INTO app_squery (query, person) VALUES (25, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-04-29, "вечер", "8 часов", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (26, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-05-05, "ночь", "1 часов", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (27, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-05-02, "ночь", "49 минут", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Настольные игры", 2015-04-22, "день", "10 минут", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (29, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Настольные игры", 2015-05-05, "вечер", "1 часов", "Досуг", True, True);
INSERT INTO app_squery (query, person) VALUES (30, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-04-23, "день", "7 часов", "Досуг", True, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Конспекты/задания", 2015-05-04, "день", "12 минут", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Коньки/ролики", 2015-05-04, "день", "12 минут", "Досуг", False, False);
INSERT INTO app_squery (query, person) VALUES (33, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "МФУ", 2015-04-30, "утро", "40 минут", "Досуг", True, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-04-28, "ночь", "28 минут", "Досуг", False, True);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Коньки/ролики", 2015-04-25, "день", "6 часов", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (36, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-24, "утро", "6 часов", "Досуг", True, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-04-25, "утро", "21 минут", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (38, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-05-07, "день", "21 минут", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (39, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Cпорт инвентарь", 2015-05-05, "день", "25 минут", "Досуг", True, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Игровые приставки", 2015-05-01, "утро", "7 часов", "Досуг", False, False);
INSERT INTO app_squery (query, person) VALUES (41, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Хоз. предметы", 2015-04-24, "утро", "10 минут", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (42, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Велики", 2015-05-06, "ночь", "7 часов", "Досуг", True, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-04-29, "ночь", "8 часов", "Досуг", False, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Велики", 2015-04-29, "день", "26 минут", "Досуг", False, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Фото/видео техника", 2015-05-02, "вечер", "6 часов", "Досуг", False, False);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-05-04, "утро", "1 часов", "Досуг", False, True);
INSERT INTO app_squery (query, person) VALUES (47, 1);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (2, "Конспекты/задания", 2015-05-07, "ночь", "17 минут", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (48, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Хоз. предметы", 2015-04-23, "утро", "5 часов", "Досуг", True, False);
INSERT INTO app_squery (query, person) VALUES (49, 2);
INSERT INTO app_query (who, need, time, dayPart, duration, description, compelete, cancel) VALUES (1, "Игровые приставки", 2015-04-26, "ночь", "16 минут", "Досуг", True, False);
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Выставки/семинары", 2015-04-28, "день", , "КПМ", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-28, "вечер", , "Конфитюр", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-26, "утро", , "РИО", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-24, "утро", , "Боталка", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Поездки в магазин", 2015-05-02, "утро", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-05-02, "ночь", , "Конфитюр", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Остальное", 2015-05-01, "ночь", , "Боталка", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-05-04, "вечер", , "Боталка", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Спортивные игры", 2015-04-23, "утро", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-29, "утро", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Выставки/семинары", 2015-04-25, "вечер", , "КПМ", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Вечера настольных игр", 2015-04-29, "утро", , "Боталка", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Вечера настольных игр", 2015-04-27, "день", , "КПМ", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Кино", 2015-04-22, "день", , "КПМ", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Кино", 2015-05-05, "вечер", , "Новодачная", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-04-22, "вечер", , "Боталка", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Кино", 2015-05-07, "утро", , "Роща", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Транспортные маршруты", 2015-05-06, "утро", , "Новодачная", 2, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Выставки/семинары", 2015-04-22, "вечер", , "Роща", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_meeting (metType, time, dayPart, location, creator, support, money, description, link) VALUES ("Клуб/Концерт", 2015-04-27, "вечер", , "РИО", 1, "МКИ, деканат", 0, "Неизвестно", "");
INSERT INTO app_member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (2, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (17, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (8, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (5, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (15, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (17, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (16, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (13, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (18, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (6, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (15, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (9, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (2, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (3, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (4, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (14, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (11, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (1, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (19, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (10, 1, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (7, 2, 0);
INSERT INTO app_member (meeting, user, donate) VALUES (12, 2, 0);
INSERT INTO app_gallery (meet, uploader, link) VALUES (9, 1, "vk.com/gallery_233434432");
INSERT INTO app_gallery (meet, uploader, link) VALUES (11, 2, "vk.com/gallery_233434477");
INSERT INTO app_gallery (meet, uploader, link) VALUES (9, 2, "vk.com/gallery_233434104");
INSERT INTO app_shop (shopName) VALUES ("Технобар");
INSERT INTO app_shop (shopName) VALUES ("Чудесный Московскийсад");
INSERT INTO app_shop (shopName) VALUES ("Зеленый Ситирынок");
INSERT INTO app_shop (shopName) VALUES ("Стальной Московскийбар");
INSERT INTO app_shop (shopName) VALUES ("Зеленый сад");
INSERT INTO app_shop (shopName) VALUES ("Совершенный Ситисад");
INSERT INTO app_shop (shopName) VALUES ("Московскийрынок");
INSERT INTO app_shop (shopName) VALUES ("Святой сад");
INSERT INTO app_shop (shopName) VALUES ("Техносад");
INSERT INTO app_shop (shopName) VALUES ("Стальной Московскиймагазин");
INSERT INTO app_shoptag (shop, tag) VALUES (5, "Еда");
INSERT INTO app_shoptag (shop, tag) VALUES (9, "Растения");
INSERT INTO app_shoptag (shop, tag) VALUES (8, "Мебель");
INSERT INTO app_shoptag (shop, tag) VALUES (4, "Мебель");
INSERT INTO app_shoptag (shop, tag) VALUES (2, "Автомобили");
INSERT INTO app_shoptag (shop, tag) VALUES (8, "Мебель");
INSERT INTO app_shoptag (shop, tag) VALUES (4, "Автомобили");
INSERT INTO app_shoptag (shop, tag) VALUES (4, "Одежда");
INSERT INTO app_shoptag (shop, tag) VALUES (3, "Техника");
INSERT INTO app_shoptag (shop, tag) VALUES (4, "Растения");
INSERT INTO app_shoptag (shop, tag) VALUES (1, "Растения");
INSERT INTO app_shoptag (shop, tag) VALUES (2, "Билеты");
INSERT INTO app_shoptag (shop, tag) VALUES (2, "Техника");
INSERT INTO app_shoptag (shop, tag) VALUES (8, "Одежда");
INSERT INTO app_shoptag (shop, tag) VALUES (2, "Одежда");
INSERT INTO app_shoptag (shop, tag) VALUES (9, "Растения");
INSERT INTO app_shoptag (shop, tag) VALUES (1, "Мебель");
INSERT INTO app_shoptag (shop, tag) VALUES (6, "Растения");
INSERT INTO app_shoptag (shop, tag) VALUES (7, "Одежда");
INSERT INTO app_shoptag (shop, tag) VALUES (3, "Автомобили");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 1, "Разовая скидка", 40, 2022-03-12, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 6, "Скидочная карта", 23, 2016-03-09, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 2, "Разовая скидка", 14, 2023-06-09, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 9, "Накопительная карта", 40, 2021-03-24, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 3, "Разовая скидка", 15, 2024-08-31, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 4, "Скидочная карта", 40, 2015-01-05, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 5, "Скидочная карта", 19, 2021-11-12, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 1, "Скидочная карта", 27, 2016-01-24, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 2, "Накопительная карта", 40, 2014-03-04, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 6, "Разовая скидка", 21, 2021-05-15, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 8, "Скидочная карта", 31, 2021-08-13, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 4, "Одноразовый купон", 31, 2014-06-13, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 2, "Накопительная карта", 46, 2022-08-02, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 6, "Накопительная карта", 32, 2025-01-09, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (1, 8, "Скидочная карта", 6, 2022-12-14, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 7, "Накопительная карта", 12, 2015-10-28, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 3, "Одноразовый купон", 5, 2020-11-22, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 6, "Скидочная карта", 35, 2013-03-12, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 1, "Накопительная карта", 39, 2024-11-24, "скидка");
INSERT INTO app_discount (owner, shop, discountType, discount, expTime, description) VALUES (2, 4, "Одноразовый купон", 38, 2024-06-22, "скидка");
